[package]
name = "clisay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
arrayvec = "0.7.6"
fnv = "1.0.7"
nohash-hasher = "0.2.0"
regex = "1.11.1"
smallvec = "1.14.0"
static_str_ops = "0.1.2"

[dev-dependencies]
criterion = "0.5.1"

trybuild = "1.0.103"

[profile.release]
debug = true

[[bench]]
name = "fib"
harness = false